name: meditation_app
description: "meditation_app"

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter
  
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  freezed: ^2.4.5
  build_runner: ^2.4.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/